# Generated by Django 4.1.7 on 2023-04-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_comment_product_chinesecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesecomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinesecomments', to='store.chinesecategory'),
        ),
    ]
