# Generated by Django 4.1.7 on 2023-04-18 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_chinacomment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinacomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chinacomments', to='store.chinesecategory'),
        ),
    ]
