# Generated by Django 4.1.7 on 2023-04-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_hindicomment_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
